source 'https://github.com/CocoaPods/Specs.git' 

use_frameworks!
platform :ios,'8.0'

target :'test' do

pod 'ReactiveCocoa', '~> 2.5'
pod 'MJExtension', '~> 3.0.10'
pod 'SVProgressHUD'
pod 'MJRefresh', '~> 3.1.0'
pod 'SDWebImage', '~> 3.7.5'
pod 'Masonry', '~> 0.6.4'


end
